### ISSUE TITLE
Failing override peer dependency

### ISSUE THREAD

**Issue by ChangJoo-Park** [Tahul/nuxt-use-motion#1]
It failed when `npm install --save nuxt-use-motion`. 

Error message. 

```bash
➜   npm install --save nuxt-use-motion     
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @vue/composition-api@undefined
npm WARN node_modules/nuxt-use-motion/node_modules/@vue/composition-api
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @vue/composition-api@">=1.x" from @vueuse/motion@1.0.4
npm WARN node_modules/nuxt-use-motion/node_modules/@vueuse/motion
npm WARN   @vueuse/motion@"latest" from nuxt-use-motion@1.0.4
npm WARN   node_modules/nuxt-use-motion
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/composition-api@>=1.x.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/changjoopark/.npm/_logs/2021-02-23T14_51_31_279Z-debug.log
```

this project has `@nuxt/composition-api` and `@vue/composition-api`. Does anyone met this error when install?

**Comment by Tahul** [comment]
Hello @ChangJoo-Park ; could you provide a little bit more context ?

What is your package.json ?

Why does your project has both @nuxt/composition-api and @vue/composition-api ?

**Comment by ChangJoo-Park** [comment]
Thanks for response @Tahul ! This is whole my package.json

```json
{
  "name": "girok",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@nuxt/content": "^1.11.1",
    "@nuxtjs/axios": "^5.12.5",
    "@nuxtjs/composition-api": "^0.20.2",
    "@vue/composition-api": "^1.0.0-rc.2",
    "core-js": "^3.8.3",
    "nuxt": "^2.14.12"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^3.4.2",
    "@tailwindcss/postcss7-compat": "^2.0.3",
    "@vue/test-utils": "^1.1.2",
    "autoprefixer": "^9.8.6",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^26.6.3",
    "jest": "^26.6.3",
    "postcss": "^7.0.35",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.3",
    "vue-jest": "^3.0.4"
  }
}
```

I need @nuxt/composition-api and @vue/composition-api both for using their own methods.  I try to only with `@nuxt/composition-api`. It failed too. You didn't met this problem?

**Comment by Tahul** [comment]
I fail to reproduce, could you give me access to the repository maybe ?

Thank you a lot for your feedback, I hope we can get it to work for you soon.

**Comment by ChangJoo-Park** [comment]
Reproduce repository here https://github.com/ChangJoo-Park/nuxt-use-motion-issue-01

I added error log from `npm install` https://github.com/ChangJoo-Park/nuxt-use-motion-issue-01/blob/main/error.log 

I just create this repo with `npx create-nuxt-app`  and add @nuxt/composition-api.

**Comment by Tahul** [comment]
Thank you a lot ChangJoo, I need to figure out something, this issue will be fixed by tomorrow.

Sorry for the inconvenience.

**Comment by Tahul** [comment]
Hello @ChangJoo-Park,

The issue is fixed in the latest version (1.0.7), could you give it a try and tell me if it is going okay for you?

Thank you for your patience. 🙏

**Comment by ChangJoo-Park** [comment]
Hello @Tahul !

Can you check this error? I cannot find package of latesst version (1.0.7) in npmjs. So I use github url directly.
I try to install 1.0.6 and 1.0.7 both. It installed successfully.

But I met another problem. 

```bash
nuxt-use-motion-issue-01 on  main [!] via ⬢ v14.15.5 took 5s
❯ npm run dev

> sample_app@1.0.0 dev C:\Users\ChangJoo Park\Documents\GitHub\nuxt-use-motion-issue-01
> nuxt


 WARN  Module nuxt-use-motion not found. Please ensure nuxt-use-motion is in devDependencies and installed. HINT: During build step, for npm/yarn, NODE_ENV=production or --production should NOT be used.                                                                   10:35:26  


 FATAL  Cannot find module 'C:\Users\ChangJoo Park\Documents\GitHub\nuxt-use-motion-issue-01\node_modules\nuxt-use-motion\dist\module.js'. Please verify that the package.json has a valid "main" entry                                                                      10:35:26  

  at tryPackage (internal/modules/cjs/loader.js:303:19)
  at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
  at Function.resolve (internal/modules/cjs/helpers.js:94:19)
  at l (node_modules\jiti\dist\jiti.js:1:8109)
  at Resolver.p [as _require] (node_modules\jiti\dist\jiti.js:1:8505)
  at Resolver.requireModule (node_modules\@nuxt\core\dist\core.js:381:29)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:182:38)
  at node_modules\@nuxt\utils\dist\utils.js:638:43
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)


   ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                                                                                            │
   │   ✖ Nuxt Fatal Error                                                                                                                                                                                       │
   │                                                                                                                                                                                                            │
   │   Error: Cannot find module 'C:\Users\ChangJoo Park\Documents\GitHub\nuxt-use-motion-issue-01\node_modules\nuxt-use-motion\dist\module.js'. Please verify that the package.json has a valid "main" entry   │
   │                                                                                                                                                                                                            │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample_app@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample_app@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm-cache\_logs\2021-02-25T01_35_27_009Z-debug.log
```

I try to find changes between 1.0.6 and 1.0.7. I can't find what is changed. Please check my [repo](https://github.com/ChangJoo-Park/nuxt-use-motion-issue-01). I followed the instruction in the README.md

**Comment by Tahul** [comment]
Hello @ChangJoo-Park ;

Please try using 1.0.8, this should fix your problem.

**Comment by ChangJoo-Park** [comment]
> Hello @ChangJoo-Park ;
> 
> Please try using 1.0.8, this should fix your problem.

Thank you for your hard work! It solved.  but not working motion directives. It is continuing discuss on #2.
