### ISSUE TITLE
Bug: Module should export a function: @nuxtjs/composition-api 

### ISSUE THREAD

**Issue by chrispreisler** [Tahul/nuxt-use-motion#7]
Hey guys,

I would like to try this awesome library with nuxt. I installed the nuxt-composition-api and also the nuxt-use-motion package. When I start the development mode I get the following error. I also only get this error, when adding the "nuxt-use-motion" library to the buildModules. The composition-api plugin is working as intended.

` ```
FATAL  Module should export a function: @nuxtjs/composition-api                                            

  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:217:13)
  at ModuleContainer.nuxtModule (node_modules/nuxt-use-motion/dist/module.js:25:14)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
````

I also created a Sandbox example, showing the problem. Did I have forget anything? I understood that I only have to add both libraries to the buildModules in the nuxt.config.js

https://codesandbox.io/s/bold-worker-vk0n4?file=/nuxt.config.js

Thanks so much for your help.

Best regards
Chris

**Comment by chrispreisler** [comment]
Nevermind, I just saw, that I don't have to install the composition-api, because it is installed by the plugin itself.
